### ISSUE TITLE
Invalid werkzeug url_quote reference

### ISSUE THREAD

**Issue by DavidHwu** [mitsuhiko/flask-openid#41]
Attached is a screen shot of the url_quote import error from werkzeug for url_quote.
Looking this up in werkzeug I also provided a simple fix.

If I am using an incompatible version of werkzeug, may I suggest that you designate this in a more standard way (ie. requirements.txt or setup.py).

Thanks

![invalid url_quote for werkzeug](https://cloud.githubusercontent.com/assets/5856387/6273536/ff146f5a-b824-11e4-80e8-ae459baee8e3.png)

![fixed werkzeug url_quote ref](https://cloud.githubusercontent.com/assets/5856387/6273540/02ea31f0-b825-11e4-871c-0f34790c5da2.png)

**Comment by puiterwijk** [comment]
Thanks for this report.
Importing it from that path does actually work in a python runtime (at least for me with werkzeug 0.9 and 0.10), but I did pick up your fix as that's the documented path.

This will be fixed in release 1.2.5 onwards.
