### ISSUE TITLE
The example doesn't work with aol and livejournal

### ISSUE THREAD

**Issue by cygmris** [mitsuhiko/flask-openid#46]
When I submit the form, it does normally direct brower to the aol openid confirm page. But after I confirm it and redirect to http://locahost:5000/login, the application response a http 500 error to my browser.

I was wonder if it's the openid platform issue. so I move my step to using livejournal to do the test.But the error still remains the same as aol before.

Tried on both Python2.7 and Python3

**Comment by puiterwijk** [comment]
Is there a traceback displayed in the console at the time of the 500 server error?
