### ISSUE TITLE
ERROR:root:Missing required parameter in response

### ISSUE THREAD

**Issue by qwexvf** [mitsuhiko/flask-openid#48]
Hello, Thanks for a great extension!
somehow i got this issue 
```
`ERROR:root:Missing required parameter in response from https://steamcommunity.com/openid/login: ('http://specs.openid.net/auth/2.0', 'assoc_type')
Traceback (most recent call last):
  File "/home/vagrant/.linuxbrew/var/pyenv/versions/venv351/lib/python3.5/site-packages/openid/message.py", line 455, in getArg
    return self.args[args_key]
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.linuxbrew/var/pyenv/versions/venv351/lib/python3.5/site-packages/openid/consumer/consumer.py", line 1283, in _requestAssociation
    assoc = self._extractAssociation(response, assoc_session)
  File "/home/vagrant/.linuxbrew/var/pyenv/versions/venv351/lib/python3.5/site-packages/openid/consumer/consumer.py", line 1400, in _extractAssociation
    OPENID_NS, 'assoc_type', no_default)
  File "/home/vagrant/.linuxbrew/var/pyenv/versions/venv351/lib/python3.5/site-packages/openid/message.py", line 458, in getArg
    raise KeyError((namespace, key))
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')`
```
Thanks.

**Comment by qwexvf** [comment]
this is the code i used.
`@app.route('/login')
@openid.loginhandler
def login():
    if session.get('logged_in'):
        return redirect(openid.get_next_url())
    return openid.try_login("http://steamcommunity.com/openid")


@openid.after_login
def create_or_login(resp):
    import re
    steamid_re = re.compile("steamcommunity.com/openid/id/(.*?)$")
    match = steamid_re.search(resp.identity_url)
    steamid = match.group(1)
    steam_data = get_steam_userinfo(steamid)
    session['logged_in'] = True
    session['steamid'] = steamid
    session['username'] = steam_data['personaname']
    session['avatar'] = steam_data['avatarmedium']

    # Check user exist on database
    exists_user = db.session.query(db.exists().where(User.username == session.get('username'))).scalar()

    # Create user row
    if not exists_user:
        user = User(session.get('username'), None, session.get('steamid'))
        db.session.add(user)
        db.session.commit()

    return redirect(openid.get_next_url())`

**Comment by gabrielfgularte** [comment]
+1

Same problem here...

**Comment by mightydok** [comment]
+1

**Comment by qwexvf** [comment]
HI, i thought there will be no fix for this. so i decided to implement steam openid login without flask-openid. and its working perfectly :D

**Comment by logeable** [comment]
+1

**Comment by PierrePaul** [comment]
+1

**Comment by Kladdkaka** [comment]
+1

**Comment by gabrielfgularte** [comment]
@qwexvf Could you explain how you did it? I'm really stuck here. Thanks! :)

**Comment by qwexvf** [comment]
@gabrielfgularte sorry for the delay respond,
basically i just get rid of the Library and i implemented it by self.
something like 

```Python
@auth.route('/steam', methods=['GET'])
def steam(request):
    steam_openid_url = 'https://steamcommunity.com/openid/login'
    params = {
        'openid.ns': "http://specs.openid.net/auth/2.0",
        'openid.identity': "http://specs.openid.net/auth/2.0/identifier_select",
        'openid.claimed_id': "http://specs.openid.net/auth/2.0/identifier_select",
        'openid.mode': 'checkid_setup',
        'openid.return_to': 'http://192.168.33.10:8080/create_or_login', # put your url where you want to be redirect
        'openid.realm': 'http://192.168.33.10:8080/' # not sure what it is
    }
    param_string = parse.urlencode(params)
    auth_url = steam_openid_url + "?" + param_string
    return redirect(auth_url)
```
when the user returns to given url (openid.return_to) we'll get a steamid so we use it get their information

to get a information i used a defined a simple function in my helpers

```Python
@app.route('/account-setup', methods=['GET', 'POST'])
def create_or_login():
    steam_id_re = re.compile('steamcommunity.com/openid/id/(.*?)$')
    match = steam_id_re.search(dict(request.args)['openid.identity'][0])
    steamid = match.group(1)
    steam_data = get_steam_user_info(steamid)
    ...
```

get steam data function

```Python
def get_steam_user_info(steam_id):
    key = {
        'key': 'YOUR_STEAM_API_KEY',
        'steamids': steam_id # from who you want to get the information. if you are giving a array, you need to change some code here.
    }
    url = 'http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0001/?%s' \
          % parse.urlencode(key)
    rv = ujson.load(request.urlopen(url))
    return rv['response']['players']['player'][0] or {}
```

i hope this will help....

**Comment by gabrielfgularte** [comment]
@qwexvf No problem! :)

Correct if I'm wrong, but, if I know your steamid (and that isn't hard to find using sites like https://steamid.io/ etc) and I fake a POST to your API on `/account-setup`, I wouldn't be able to login or create an account as you?

**Comment by qwexvf** [comment]
@gabrielfgularte Nice catch! i didn't think about it! let me implement a function that validate incoming payload! give me a moment!

**Comment by qwexvf** [comment]
There you go.
```Python
def validate(signed_params):
    import requests
    import json
    from urllib import parse
    steam_login_url_base = "https://steamcommunity.com/openid/login"

    params = {
        "openid.assoc_handle": signed_params["openid.assoc_handle"],
        "openid.sig": signed_params["openid.sig"],
        "openid.ns": signed_params["openid.ns"],
        "openid.mode": "check_authentication"
    }

    signed_params.update(params)

    signed_params["openid.mode"] = "check_authentication"
    signed_params["openid.signed"] = signed_params["openid.signed"]

    r = requests.post(steam_login_url_base, data=signed_params)

    if "is_valid:true" in r.text:
        return True

    # this fucntion should always return false if the payload is not valid
    return False
```
Note: how to use it.
when the steam redirect you to the given url i comes with a payload.
we want to pass that payload and check if it a valid payload

example:

```Python

@app.route('/setup', methods=['GET'])
def setup(request):
    is_vliad = validate(request.args) # return a boolean
    if is_valid:
        # do your stuff here
        pass
    else:
        # return to other page or try to login again.
        pass

    return text(valid)
```

**Comment by gabrielfgularte** [comment]
Excellent!

But why do you update a dictionary with data that you gathered from it? It is just to assign the `openid.mode`?

```
...
params = {
        "openid.assoc_handle": signed_params["openid.assoc_handle"],
        "openid.sig": signed_params["openid.sig"],
        "openid.ns": signed_params["openid.ns"],
        "openid.mode": "check_authentication"
    }

signed_params.update(params)
...
```

**Comment by qwexvf** [comment]
@gabrielfgularte i did't read the openid docs well, but what i understood is that everything that came from payload should be the same(which come with openid.signed) object when making the post request. so i just took the important parts and updated the payload.

Btw, as soon you said people can register as another user, i wonder if other steam login based application has that kind of validator or something lol. if they don't then thats a big problem.

**Comment by gabrielfgularte** [comment]
You're right about it, every value must be exactly the same. But I'm not sure if what you did ensures that. Every library that I decide to take a closer look, to understand how the "connection" between the End-User, the Client and the OpenID Provider, has a thousand and thousand of lines that gives me headaches. That's why I don't know for sure if you can do this using a 10line code. Maybe you did it, and the other lines that I read was about other library functionality...

I've changed to Python Social Auth package instead of this one. Two factors was very important for me to move:

1. The error in this issue.
2. The abstraction to do all the handshakes that a OpenID authentication needs.

I recommend that you take a look into this repo https://github.com/python-social-auth. I've migrated to Django, but I think that Flask will work pretty well.

**Comment by qwexvf** [comment]
Right. well, these libraries are probably compatible with other authentication that requires openid not only steam. so they are complicated. but once you read carefully read the openid final docs we'll notice that you can implement it very simple(if you're making for something you and specific app. in this case steam). 

but yes, i was at school and i implemented in rush my verification method lol. sorry about it.
maybe this will be a good example for a simple app openid authentication. so i will do some tests and upload to gist or something. in anyways thanks for noticing me that people can login as others haha!
these are the links i followed when i implemented the above method.

https://openid.net/specs/openid-authentication-2_0.html#requesting_authentication
https://openid.net/specs/openid-authentication-2_0.html#verification
https://openid.net/specs/openid-authentication-2_0.html#security_considerations

Thank you.

**Comment by gabrielfgularte** [comment]
Maybe you're right. And you're welcome! :)

Thank you!

**Comment by amir3code** [comment]
@gabrielfgularte Can you explain how did you implement this with `python-social-auth` package? I cant understand that package and dont know how to implement in it.
