### ISSUE TITLE
Error fetching XRDS document: <urlopen error [Errno -5] No address associated with hostname>

### ISSUE THREAD

**Issue by ETzero** [mitsuhiko/flask-openid#49]
i run the example in my computer,but it prompt:Error fetching XRDS document: <urlopen error [Errno -5] No address associated with hostname> after input 'xkk' or 'xkk@email.com' and sign in.

my flask-openid.db have two records like this:
1|wdd|wdd@email.com|8899
2|xkk|xkk@email.com|3432

Why am I getting this error, and how do I fix it?

**Comment by puiterwijk** [comment]
How did the entries in the database get created, did you do that manually?

When using the example, you are supposed to enter the URL of the identity provider or of your OpenID identity: all identities in OpenID are URLs.

**Comment by ETzero** [comment]
oh, i get it. thank you
