### ISSUE TITLE
Use environment marker instead of checking python version programatically.

### ISSUE THREAD

**Issue by mbelang** [mitsuhiko/flask-openid#54]
This package checks the installed version programatically and it is not compatible with poetry as mentionned here: https://github.com/sdispater/poetry/issues/1287

Could the lib use dependency markers instead which follows [PEP-508](https://www.python.org/dev/peps/pep-0508/#environment-markers).

**Comment by leonsmith** [comment]
Is this project dead with the last commit being 4 years ago?

**Comment by sethwoodworth** [comment]
Oof. This makes using Poetry difficult (which respects env markers and _not_ setup.py) with anything requiring this library.
