### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext' when running the example

### ISSUE THREAD

**Issue by nessita** [mitsuhiko/flask-openid#57]
Following the instructions to run the example, I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'flask.ext'

Dependencies:

Flask==1.1.2
Flask-OpenID==1.2.5
python3-openid==3.2.0

**Comment by Lauenburg** [comment]
You can rename the import to `flask.ext.openid` to `flask_openid`.
