### ISSUE TITLE
build failed because of unsupported options in setuptools

### ISSUE THREAD

**Issue by getumen** [mitsuhiko/flask-openid#59]
flask-openid build failed.
```
error in Flask-OpenID setup command: use_2to3 is invalid.
```
dependency:
setuptools: 58.0.2

From setuptools v58.0.0, the `use_2to3` option is no longer sopported.
https://github.com/pypa/setuptools/commit/9f75850ec2455718c4c470c16c4c15139deef624

**Comment by jaraco** [comment]
One option that would largely alleviate the pain would be to release a wheel for Python 3 of the latest version. Then pip would install it without touching Setuptools.

**Comment by potiuk** [comment]
Similar discussion here: https://github.com/mitsuhiko/flask-openid/pull/60#issuecomment-915439748 - we might release 2to3 processed code as Python3-only package.
